apiVersion: eks.services.k8s.aws/v1alpha1
kind: Addon
metadata:
  name: {{ .Values.cluster.name }}-coredns
spec:
  name: coredns
  addonVersion: v1.8.7-eksbuild.2
  clusterName: {{ .Values.cluster.name }} 
