apiVersion: eks.services.k8s.aws/v1alpha1
kind: Addon
metadata:
  name: {{ .Values.cluster.name }}-vpc-cni
  namespace: {{ template "tenant-cluster.namespace" . }}
spec:
  name: vpc-cni
  addonVersion: v1.10.4-eksbuild.1
  clusterName: {{ .Values.cluster.name }}
